"""
BibTeX file management for paper generation.
"""

from typing import List, Dict, Any
from pathlib import Path
import re
from loguru import logger
from ..utils.config import get_bibtex_path
from ..utils.validators import PaperValidator


class BibTeXManager:
    """Manage BibTeX entries for papers."""

    def __init__(self):
        """Initialize BibTeX manager."""
        self.validator = PaperValidator()

    def _clean_bibtex_string(self, text: str) -> str:
        """
        Clean text for BibTeX entry.

        Args:
            text: Input text

        Returns:
            str: Cleaned text
        """
        if not text:
            return ""

        # Remove newlines and extra spaces
        text = " ".join(text.split())

        # Escape special characters for BibTeX
        # Braces and backslashes need special handling
        text = text.replace("\\", "\\textbackslash ")
        text = text.replace("{", "\\{")
        text = text.replace("}", "\\}")
        text = text.replace("&", "\\&")
        text = text.replace("%", "\\%")
        text = text.replace("$", "\\$")
        text = text.replace("#", "\\#")
        text = text.replace("_", "\\_")

        return text

    def _generate_citation_key(self, paper: Dict[str, Any]) -> str:
        """
        Generate unique citation key for paper.

        Args:
            paper: Paper dictionary

        Returns:
            str: Citation key
        """
        # Get first author's last name
        authors = paper.get("authors", [])
        if authors:
            first_author = authors[0]
            # Extract last name (simple heuristic: last word)
            last_name = first_author.split()[-1]
            # Remove special characters
            last_name = re.sub(r'[^a-zA-Z]', '', last_name)
        else:
            last_name = "Unknown"

        # Get year
        year = paper.get("year", "2025")

        # Get ArXiv ID for uniqueness
        arxiv_id = paper.get("arxiv_id", "")
        # Extract numeric part
        arxiv_number = re.sub(r'[^0-9]', '', arxiv_id)[-4:] if arxiv_id else "0000"

        citation_key = f"{last_name}{year}_{arxiv_number}"

        return citation_key

    def generate_bibtex_entry(self, paper: Dict[str, Any]) -> str:
        """
        Generate BibTeX entry for a single paper.

        Args:
            paper: Paper dictionary

        Returns:
            str: BibTeX entry
        """
        citation_key = self._generate_citation_key(paper)

        # Prepare fields
        title = self._clean_bibtex_string(paper.get("title", ""))
        abstract = self._clean_bibtex_string(paper.get("abstract", ""))

        # Format authors
        authors = paper.get("authors", [])
        author_str = " and ".join(authors) if authors else "Unknown"

        # Get other fields
        year = paper.get("year", "2025")
        arxiv_id = paper.get("arxiv_id", "")
        primary_category = paper.get("primary_category", "cs.DC")

        # Build BibTeX entry
        entry = []
        entry.append(f"@misc{{{citation_key},")
        entry.append(f"  title = {{{{{title}}}}},")
        entry.append(f"  author = {{{author_str}}},")
        entry.append(f"  year = {{{year}}},")
        entry.append(f"  eprint = {{{arxiv_id}}},")
        entry.append(f"  archivePrefix = {{arXiv}},")
        entry.append(f"  primaryClass = {{{primary_category}}},")

        # Add URL
        if arxiv_id:
            url = f"https://arxiv.org/abs/{arxiv_id}"
            entry.append(f"  url = {{{url}}},")

        # Add abstract as note
        if abstract:
            # Truncate if too long
            if len(abstract) > 500:
                abstract = abstract[:497] + "..."
            entry.append(f"  note = {{{{{abstract}}}}}")

        entry.append("}")

        bibtex_entry = "\n".join(entry)

        return bibtex_entry

    def generate_bibtex_from_papers(self, papers: List[Dict[str, Any]]) -> str:
        """
        Generate BibTeX file content from list of papers.

        Args:
            papers: List of paper dictionaries

        Returns:
            str: Complete BibTeX file content
        """
        logger.info(f"Generating BibTeX entries for {len(papers)} papers")

        entries = []

        # Add header comment
        entries.append("% BibTeX file generated by ArXiv Edge Computing Analyzer")
        entries.append("% Edge of ArXiv: Cutting-Edge Computing Research Trends in 2025")
        entries.append("% Generated on " + __import__('datetime').datetime.now().strftime("%Y-%m-%d"))
        entries.append("")

        # Generate entries
        for paper in papers:
            entry = self.generate_bibtex_entry(paper)
            entries.append(entry)
            entries.append("")  # Blank line between entries

        bibtex_content = "\n".join(entries)

        logger.info(f"Generated BibTeX content with {len(papers)} entries")
        return bibtex_content

    def save_bibtex(self, content: str, filename: str = None) -> Path:
        """
        Save BibTeX content to file.

        Args:
            content: BibTeX file content
            filename: Output filename (default: all_papers_2025.bib)

        Returns:
            Path: Path to saved file
        """
        if filename is None:
            filepath = get_bibtex_path("all_papers_2025")
        else:
            filepath = get_bibtex_path(filename)

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        logger.info(f"Saved BibTeX file to {filepath}")
        return filepath

    def create_cited_bibtex(self, papers: List[Dict[str, Any]],
                            cited_keys: List[str]) -> str:
        """
        Create BibTeX file with only cited papers.

        Args:
            papers: All papers
            cited_keys: List of citation keys that are actually cited

        Returns:
            str: BibTeX content with only cited papers
        """
        logger.info(f"Creating BibTeX file with {len(cited_keys)} cited papers")

        # Generate all entries
        all_bibtex = self.generate_bibtex_from_papers(papers)

        # Filter to only cited entries
        # This is a simplified approach - in practice, you'd parse and filter properly
        cited_entries = []

        for paper in papers:
            citation_key = self._generate_citation_key(paper)
            if citation_key in cited_keys:
                entry = self.generate_bibtex_entry(paper)
                cited_entries.append(entry)

        # Add header
        header = [
            "% Cited references from Edge of ArXiv review paper",
            "% Generated on " + __import__('datetime').datetime.now().strftime("%Y-%m-%d"),
            ""
        ]

        bibtex_content = "\n".join(header + ["\n".join(cited_entries)])

        return bibtex_content

    def generate_all_bibtex_files(self, papers: List[Dict[str, Any]]):
        """
        Generate all BibTeX files.

        Args:
            papers: List of all papers
        """
        logger.info("Generating all BibTeX files")

        # All papers
        all_bibtex = self.generate_bibtex_from_papers(papers)
        self.save_bibtex(all_bibtex, "all_papers_2025")

        # Highly relevant papers (first 50 by some criteria)
        # For now, just take first 50
        relevant_papers = papers[:50] if len(papers) > 50 else papers
        relevant_bibtex = self.generate_bibtex_from_papers(relevant_papers)
        self.save_bibtex(relevant_bibtex, "highly_relevant")

        logger.info("All BibTeX files generated")

    def get_citation_key(self, paper: Dict[str, Any]) -> str:
        """
        Get citation key for a paper.

        Args:
            paper: Paper dictionary

        Returns:
            str: Citation key
        """
        return self._generate_citation_key(paper)


def main():
    """Main function for testing BibTeX manager."""
    print("BibTeX manager module loaded successfully")


if __name__ == "__main__":
    main()
